# Generated by Django 5.1.6 on 2026-10-08 17:44

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('emoji', models.CharField(default='🎬', max_length=10)),
                ('genre', models.CharField(default='Hành động', max_length=100)),
                ('duration', models.IntegerField(default=120)),
                ('rating', models.FloatField(default=8.5)),
                ('start_date', models.CharField(blank=True, default='20/02/2026', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Đang chiếu'), ('upcoming', 'Sắp chiếu')], default='active', max_length=20)),
                ('c1', models.CharField(default='#1a0a2e', max_length=30)),
                ('c2', models.CharField(default='#3d1f5e', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('IMAX', 'IMAX'), ('4DX', '4DX'), ('2D', '2D'), ('3D', '3D')], default='2D', max_length=20)),
                ('total_seats', models.IntegerField(default=120)),
                ('status', models.CharField(default='Hoạt động', max_length=50)),
                ('usage_pct', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('role', models.CharField(choices=[('Admin', 'Administrator'), ('Staff', 'Nhân viên rạp'), ('User', 'Khách hàng')], default='User', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.CharField(default='Khách hàng', max_length=150)),
                ('role', models.CharField(default='Khách hàng VIP', max_length=50)),
                ('stars', models.IntegerField(default=5)),
                ('text', models.TextField()),
                ('date', models.CharField(default='Hôm nay', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='cinema.movie')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.CharField(default='2026-02-27', max_length=20)),
                ('start_time', models.CharField(default='19:00', max_length=10)),
                ('price_std', models.IntegerField(default=90000)),
                ('price_vip', models.IntegerField(default=130000)),
                ('price_sweet', models.IntegerField(default=220000)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='cinema.movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='cinema.room')),
            ],
            options={
                'ordering': ['show_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=50, unique=True)),
                ('customer', models.CharField(default='Khách hàng', max_length=150)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('movie', models.CharField(max_length=200)),
                ('room', models.CharField(default='Phòng 1 - IMAX', max_length=100)),
                ('time', models.CharField(default='19:00', max_length=50)),
                ('seats', models.CharField(max_length=200)),
                ('total', models.CharField(default='0đ', max_length=50)),
                ('total_amount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(default='Tiền mặt', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Đã đặt'), ('used', 'Đã check-in'), ('cancelled', 'Đã hủy')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('showtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='cinema.showtime')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('BOOKED', 'Đã đặt'), ('HELD', 'Đang giữ')], default='BOOKED', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='cinema.showtime')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_items', to='cinema.ticket')),
            ],
            options={
                'unique_together': {('showtime', 'seat_id')},
            },
        ),
    ]
