# Generated by Django 5.1.6 on 2026-08-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa mềm')),
                ('ticket_code', models.CharField(max_length=50, unique=True, verbose_name='Mã vé QR')),
                ('total_ticket_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền vé')),
                ('total_fnb_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền bắp nước')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền giảm giá')),
                ('final_total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng thanh toán')),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Thẻ tín dụng (Visa/Master)'), ('MOMO', 'Ví điện tử MoMo'), ('VNPAY', 'VNPay QR'), ('ZALOPAY', 'ZaloPay'), ('CASH_AT_COUNTER', 'Tiền mặt tại quầy')], default='CREDIT_CARD', max_length=30, verbose_name='Phương thức thanh toán')),
                ('booking_status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('CONFIRMED', 'Đã đặt vé'), ('CHECKED_IN', 'Đã check-in'), ('CANCELLED', 'Đã hủy vé')], default='CONFIRMED', max_length=30, verbose_name='Trạng thái đơn hàng')),
            ],
            options={
                'verbose_name': 'Vé & Đơn hàng',
                'verbose_name_plural': 'Danh sách vé & đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='BookingCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa mềm')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá')),
            ],
            options={
                'verbose_name': 'Bắp nước trong đơn',
                'verbose_name_plural': 'Danh sách bắp nước trong đơn',
            },
        ),
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa mềm')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá ghế')),
            ],
            options={
                'verbose_name': 'Ghế trong đơn',
                'verbose_name_plural': 'Danh sách ghế trong đơn',
            },
        ),
    ]
