# Generated by Django 5.1.6 on 2026-08-06 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='showtimes.showtime', verbose_name='Suất chiếu'),
        ),
    ]
