# Generated by Django 5.1.6 on 2026-08-06 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('cinemas', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='booking',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.voucher', verbose_name='Mã giảm giá'),
        ),
        migrations.AddField(
            model_name='bookingcombo',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='bookings.booking', verbose_name='Đơn hàng'),
        ),
        migrations.AddField(
            model_name='bookingcombo',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.combofnb', verbose_name='Combo bắp nước'),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.booking', verbose_name='Đơn hàng'),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.seat', verbose_name='Ghế ngồi'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingseat',
            unique_together={('booking', 'seat')},
        ),
    ]
