# Generated by Django 5.1.6 on 2026-08-06 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa mềm')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('price_standard', models.DecimalField(decimal_places=0, default=100000, max_digits=12, max_length=10, verbose_name='Giá vé thường')),
                ('price_vip', models.DecimalField(decimal_places=0, default=150000, max_digits=12, max_length=10, verbose_name='Giá vé VIP')),
                ('price_sweetbox', models.DecimalField(decimal_places=0, default=200000, max_digits=12, max_length=10, verbose_name='Giá vé Sweetbox')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie', verbose_name='Phim')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='cinemas.room', verbose_name='Phòng chiếu')),
            ],
            options={
                'verbose_name': 'Suất chiếu',
                'verbose_name_plural': 'Danh sách suất chiếu',
            },
        ),
    ]
