# Generated by Django 5.1.6 on 2026-08-06 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa mềm')),
                ('name', models.CharField(max_length=255, verbose_name='Tên cụm rạp')),
                ('address', models.CharField(max_length=500, verbose_name='Địa chỉ')),
                ('city', models.CharField(max_length=100, verbose_name='Thành phố')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
            ],
            options={
                'verbose_name': 'Cụm rạp',
                'verbose_name_plural': 'Danh sách cụm rạp',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa mềm')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phòng chiếu')),
                ('room_type', models.CharField(choices=[('STANDARD_2D', 'Standard 2D'), ('DIGITAL_3D', 'Digital 3D'), ('IMAX_3D', 'IMAX 3D'), ('DOLBY_4DX', '4DX Experience')], default='STANDARD_2D', max_length=30, verbose_name='Loại phòng')),
                ('total_seats', models.PositiveIntegerField(default=100, verbose_name='Tổng số ghế')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='cinemas.cinema', verbose_name='Cụm rạp')),
            ],
            options={
                'verbose_name': 'Phòng chiếu',
                'verbose_name_plural': 'Danh sách phòng chiếu',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa mềm')),
                ('seat_number', models.CharField(max_length=10, verbose_name='Số ghế (A1, A2...)')),
                ('row_name', models.CharField(max_length=5, verbose_name='Hàng ghế')),
                ('col_index', models.PositiveIntegerField(default=1, verbose_name='Cột ghế')),
                ('seat_type', models.CharField(choices=[('STANDARD', 'Ghế thường'), ('VIP', 'Ghế VIP'), ('SWEETBOX', 'Ghế đôi Sweetbox')], default='STANDARD', max_length=20, verbose_name='Loại ghế')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinemas.room', verbose_name='Phòng chiếu')),
            ],
            options={
                'verbose_name': 'Ghế ngồi',
                'verbose_name_plural': 'Danh sách ghế ngồi',
                'unique_together': {('room', 'seat_number')},
            },
        ),
    ]
