# Generated by Django 5.1.6 on 2026-08-06 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa mềm')),
                ('title', models.CharField(max_length=255, verbose_name='Tên phim')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả nội dung')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='Đạo diễn')),
                ('cast', models.CharField(blank=True, max_length=500, verbose_name='Diễn viên')),
                ('genre', models.CharField(max_length=100, verbose_name='Thể loại')),
                ('duration_mins', models.PositiveIntegerField(default=120, verbose_name='Thời lượng (Phút)')),
                ('rating', models.FloatField(default=8.0, verbose_name='Đánh giá sao')),
                ('poster_url', models.URLField(blank=True, max_length=1000, verbose_name='URL Poster')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Ngày khởi chiếu')),
                ('status', models.CharField(choices=[('SHOWING', 'Đang chiếu'), ('UPCOMING', 'Sắp chiếu'), ('STOPPED', 'Đã ngừng chiếu')], default='SHOWING', max_length=20, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Phim',
                'verbose_name_plural': 'Danh sách phim',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa mềm')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Điểm (1-5)')),
                ('comment', models.TextField(verbose_name='Bình luận')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie', verbose_name='Phim')),
            ],
            options={
                'verbose_name': 'Đánh giá phim',
                'verbose_name_plural': 'Danh sách đánh giá',
            },
        ),
    ]
