# Generated by Django 5.1.6 on 2026-08-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(default='C13', max_length=20, verbose_name='Giới hạn tuổi'),
        ),
        migrations.AddField(
            model_name='movie',
            name='badge',
            field=models.CharField(default='HOT', max_length=20, verbose_name='Nhãn dán'),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='Tiếng Anh - Phụ đề Tiếng Việt', max_length=100, verbose_name='Ngôn ngữ'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(default=2025, verbose_name='Năm sản xuất'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL Trailer YouTube'),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.PositiveIntegerField(default=500, verbose_name='Số lượt đánh giá'),
        ),
    ]
