# Generated by Django 5.1.6 on 2026-08-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComboFNB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa mềm')),
                ('name', models.CharField(max_length=255, verbose_name='Tên combo bắp nước')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả sản phẩm')),
                ('price', models.DecimalField(decimal_places=0, default=75000, max_digits=12, verbose_name='Giá bán')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
            ],
            options={
                'verbose_name': 'Combo Bắp Nước',
                'verbose_name_plural': 'Danh sách Combo Bắp Nước',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa mềm')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Phần trăm giảm (%)')),
                ('max_discount_amount', models.DecimalField(decimal_places=0, default=50000, max_digits=12, verbose_name='Giảm tối đa')),
                ('min_order_value', models.DecimalField(decimal_places=0, default=100000, max_digits=12, verbose_name='Giá trị đơn tối thiểu')),
                ('expiration_date', models.DateField(verbose_name='Hạn sử dụng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiệu lực')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Danh sách mã giảm giá',
            },
        ),
    ]
